### ISSUE TITLE
The custom integration lennoxs30 implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity.

### ISSUE THREAD

**Issue by scottgehman** [PeteRager/lennoxs30#328] opened 2024-06-15 19:42 UTC
The custom integration lennoxs30 implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity.

**Comment by PeteRager** [comment] 2024-06-16 09:56
Thank you for reporting.  This is a duplicate of #320 - see that for instructions.

**Closed by PeteRager** 2024-06-16 09:56 UTC
