### ISSUE TITLE
Emergency heat mode not available for systems with heat strips

### ISSUE THREAD

**Issue by varialflip** [PeteRager/lennoxs30#307] opened 2024-02-19 17:10 UTC
S30 with XP25 heatpump and indoor unit heat strips, 2 zone system.
Version 2024.2.0
Local connection, with diagnostics level 2. No access from the thermostat to DNS or internet

Emergency heat works fine from the thermostat but is not available from the integration.

hvac_modes: off, cool, heat, heat_cool
aux: false
supported_features: 414

there is no "has_aux" entry.

How would i start to investigate to understand why emergency heat is not available in the integration?

**Comment by PeteRager** [comment] 2024-02-19 17:34
To turn on emergency heat, you will need to call the service

CLIMATE.SET_AUX_HEAT

There is no hvac mode in home assistant for emergency heat and the integration is not allowed to add its own hvac modes.

**Comment by varialflip** [comment] 2024-02-19 17:46
Hi thanks for the answer. My climate entities aren’t available for .set_aux_heat. The feature isn’t supported for the thermostat device
![IMG_2417](https://github.com/PeteRager/lennoxs30/assets/32375469/e4f27be4-23e6-4a38-a7c7-88ba48c79218)

**Comment by varialflip** [comment] 2024-02-19 19:58
In case some of this is useful: here’s the attributes for the climate entity:

hvac_modes:
  - "off"
  - cool
  - heat
  - heat_cool
min_temp: 4.5
max_temp: 37
target_temp_step: 0.5
min_humidity: 15
max_humidity: 45
fan_modes:
  - auto
  - "on"
  - circulate
preset_modes:
  - schedule IQ
  - Critical Peak Bedrooms
  - Critical Peak
  - Main Floor Schedule
  - Bedrooms Schedule
  - away
  - cancel hold
  - cancel away mode
  - none
current_temperature: 24.5
target_temp_high: 24.5
target_temp_low: 21
current_humidity: 30
humidity: 37
fan_mode: "on"
hvac_action: idle
preset_mode: Schedule Hold
allergenDefender: false
damper: 100
demand: 0
fan: "on"
humidityMode: humidify
humOperation: "off"
tempOperation: "off"
ventilation: false
heatCoast: false
defrost: false
balancePoint: mid
aux: false
coolCoast: false
ssr: false
zoneEnabled: true
zoningMode: zoned
friendly_name: Outardes_Main Floor
supported_features: 414

**Comment by PeteRager** [comment] 2024-02-20 03:55
Thanks.  The supported features indicate that aux heat is not being detected.  That flag has a value of 64 and when I do the bitwise math it's not set.

In the device list for the integration do you have a device that correspond to the heat pump and a device that corresponds to the furnace?  If so, grab the integrations diagnostic file (settings, integrations, lennoxs30) and then look for the "download diagnostics" option on the ... menu and post it here. 

If not, we'll need to collect a message log to see exactly what is configured in your system.  Instructions for that are in the readme. 

https://github.com/PeteRager/lennoxs30?tab=readme-ov-file#reporting-bugs

**Comment by varialflip** [comment] 2024-02-20 04:12
Hi, the integration populates the devices fine if i understand correctly.
Here's the diagnostics json

[config_entry-lennoxs30-adcef55a65f12b2357bd5b503390b746.json](https://github.com/PeteRager/lennoxs30/files/14339305/config_entry-lennoxs30-adcef55a65f12b2357bd5b503390b746.json)

**Comment by PeteRager** [comment] 2024-02-20 13:41
I don't see a furnace listed.  What provides the emergency heat when the heat pump is disabled?  Does the air handler have an electric heater in it.

**Comment by varialflip** [comment] 2024-02-20 13:44
Correct, I have 20kw of heat strips in the air handler

**Comment by PeteRager** [comment] 2024-02-20 13:48
Ok.  The integration detects aux heat by seeing if you have a furnace and a heat pump.  So we'll need to update it to detect the electric panels.  We'll need to capture a message log to see how that is represented in the configuration.

**Comment by varialflip** [comment] 2024-02-20 14:50
Here's a message log : [s30.log](https://github.com/PeteRager/lennoxs30/files/14345977/s30.log)

there's mention of "emergencyHeatingOption": true

**Comment by PeteRager** [comment] 2024-02-20 15:22
Thanks.  The API is not looking at that flag.  It maybe that it got added in on a firmware update or it was missed during the initial implementation.  Either way, the API needs to get updated.

https://github.com/PeteRager/lennoxs30api/blob/e1b977c899bbfd5aad5b532f4771838efa01b383/lennoxs30api/s30api_async.py#L1699

**Comment by varialflip** [comment] 2024-02-20 15:25
Oh i see. it checks for the name "furnace" whereas my unit reports "air handler"
Maybe the flag "indoorUnitStaging": 4 describes 4 stage heating? (my electric aux heating is 4 staged)
I have no way to compare to a air handler without aux electric heat.

**Comment by PeteRager** [comment] 2024-02-20 20:08
It was a quick fix.  Created a new release 2024.2.1.  When you have time give it a test and let me know if the issue is resolved.

**Comment by varialflip** [comment] 2024-02-20 20:26
Hi! Installed the 2024.2.1_r version
I'm now able to call for aux_heat but I get this error :
[homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: turn_aux_heat_on [Main Floor] [Code [7] Reference [4] [setHvacMode - invalid hvac mode - zone [0] does not support [emergency heat]]]

**Comment by varialflip** [comment] 2024-02-20 20:43
The attribute [aux_heat: "off"] or ["on"] follows the state of the thermostat correctly when set from the thermostat.
However I can't change the state via home assistant.

**Comment by PeteRager** [comment] 2024-02-20 21:44
Looks like some progress. I missed updating the validation for that method.

**Comment by PeteRager** [comment] 2024-02-20 23:04
I've updated the API to fix that issue.  If you want to test it this is what to do:

- In you HA config edit the file config/custom_components/lennoxs30/manifest.json
- Change the api version from 0.2.13 to 0.2.14
- Save the file
- Restart HA

That should pull the new API version on restart.  Once we confirm the problem is fixed.  I'll create a new release for the integration or if you don't know how to find and edit that file - that's ok also - and I'll create a release tomorrow morning ET.

**Comment by varialflip** [comment] 2024-02-20 23:11
Works great! Many thanks for this!

**Comment by PeteRager** [comment] 2024-02-20 23:36
Great.  Thanks for your help testing.  I'll create a new release for the integration and close this issue then.

**Comment by PeteRager** [comment] 2024-03-07 01:21
New release is out.  2024.3.0

**Closed by PeteRager** 2024-03-07 01:21 UTC
Labels: bug
