### ISSUE TITLE
processMessage unknown SenderId/SystemId

### ISSUE THREAD

**Issue by jrhubott** [PeteRager/lennoxs30#164] opened 2022-06-01 23:51 UTC
I get this message over and over in my log.  This happens on 2022.6.0 and earlier version.

processMessage unknown SenderId/SystemId [KL20J72721]

I also see in the Logbook the the device connected every 30 seconds to 10 minutes

I have two thermostats - Upstairs and Downstairs

DEBUG logs follow:

2022-06-01 16:44:38 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 90,
                        "outdoorTemperatureC": 32
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:38 DEBUG (MainThread) [lennoxs30api.s30api_async] update_attr: system Id [LCC] attr [outdoorTemperatureC] value [32]
2022-06-01 16:44:38 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [True] dirtyList [['outdoorTemperatureC']]
2022-06-01 16:44:38 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 90,
                        "outdoorTemperatureC": 32
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:38 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:42 WARNING (MainThread) [homeassistant.components.utility_meter.select] The 'utility_meter.select_tariff' service has been deprecated and will be removed in HA Core 2022.7. Please use 'select.select_option' instead
2022-06-01 16:44:42 WARNING (MainThread) [homeassistant.components.utility_meter.select] The 'utility_meter.select_tariff' service has been deprecated and will be removed in HA Core 2022.7. Please use 'select.select_option' instead
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 90,
                        "outdoorTemperatureC": 32
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 90,
                        "outdoorTemperatureC": 32
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "zones": [
                    {
                        "publisher": {
                            "publisherName": "lcc"
                        },
                        "status": {
                            "fan": false,
                            "allergenDefender": false,
                            "humidity": 54,
                            "temperature": 77,
                            "damper": 0,
                            "heatCoast": false,
                            "defrost": false,
                            "humidityStatus": "good",
                            "period": {
                                "systemMode": "off",
                                "fanMode": "auto",
                                "husp": 40,
                                "sp": 73,
                                "desp": 55,
                                "csp": 70,
                                "hsp": 67,
                                "hspC": 19.5,
                                "startTime": 0,
                                "humidityMode": "off",
                                "spC": 23,
                                "cspC": 21
                            },
                            "humOperation": "off",
                            "scheduleExceptionIds": [],
                            "balancePoint": "none",
                            "tempOperation": "off",
                            "ventilation": false,
                            "demand": 0,
                            "aux": false,
                            "coolCoast": false,
                            "ssr": false,
                            "temperatureStatus": "good",
                            "temperatureC": 25
                        },
                        "id": 0
                    }
                ]
            }
        }
    ]
}
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage lennox_zone id [0]
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete lennox_zone id [0] dirty [False] dirtyList [[]]
2022-06-01 16:44:43 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 84,
                        "outdoorTemperatureC": 29
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 84,
                        "outdoorTemperatureC": 29
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 90,
                        "outdoorTemperatureC": 32
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 90,
                        "outdoorTemperatureC": 32
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:48 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:50 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "logs": {
                    "linesReadInCSV": 19,
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:50 DEBUG (MainThread) [lennoxs30api.s30api_async] processMessage complete system id [LCC] dirty [False] dirtyList [[]]
2022-06-01 16:44:52 DEBUG (MainThread) [lennoxs30api.s30api_async] {
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 84,
                        "outdoorTemperatureC": 29
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        },
        {
            "MessageId": 1,
            "SenderID": "**redacted**",
            "TargetID": "ha_prod",
            "MessageType": "PropertyChange",
            "Data": {
                "system": {
                    "status": {
                        "outdoorTemperatureStatus": "good",
                        "outdoorTemperature": 84,
                        "outdoorTemperatureC": 29
                    },
                    "publisher": {
                        "publisherName": "lcc"
                    }
                }
            }
        }
    ]
}
2022-06-01 16:44:52 ERROR (MainThread) [lennoxs30api.s30api_async] processMessage unknown SenderId/SystemId [KL20J72721]
2022-06-01 16:44:52 ERROR (MainThread) [lennoxs30api.s30api_async] processMessage unknown SenderId/SystemId [KL20J72721]

**Comment by PeteRager** [comment] 2022-06-07 21:22
Apologies, just saw this now.

This issue should be fixed in 0.2.7. Are you running that version?

**Comment by PeteRager** [comment] 2022-06-07 21:50
Actually I can see from the error message you are running 0.2.7, as in older versions it was different.  This appears to be similar to the issue fixed in #153, but something must be different.

Are you using local or cloud connection?

Do you have multiple integrations configured? 

Are you using the power diagnostics?

If you have multiple integrations configured, I’d like to have you try changing the app_id from the default to something unique for each connection.   For example ha_1 and ha_2.  Restart home assistant and we can see if the error goes away.

Assuming you have multiple connections, I’ll want message logs.  Go into the integration configuration, select the option to “log s30 messages to a separate file”, give the file a name like s30_1.log, do the same for the other integration but give it a different name like s30_2.log, you’ll need to restart or reload the integrations.   Let it run for 10 minutes or so, then post those files here (all personal info is redacted) or I can give you an email to send to.

**Comment by PeteRager** [comment] 2022-06-08 15:52
I am working on a new release out in next few days, at a minimum I will add code to not log that message continuously, though getting at the root cause would be good.

**Comment by PeteRager** [comment] 2022-06-10 15:36
The excessive logging of error messages will be fixed in a release tomorrow.

It would still be good to get to the root of the issue as it's putting additional load on your network and the S30s.

**Comment by jrhubott** [comment] 2022-06-11 02:29
I will catch the log files you are looking for this weekend. Thanks for the update.

**Closed** 2022-06-23 12:20 UTC
