### ISSUE TITLE
How to configure the Lennox LCC diagnostic mode to be 1 or 2?

### ISSUE THREAD

**Issue by rugene76** [PeteRager/lennoxs30#112] opened 2021-12-09 16:17 UTC
I love what you're doing here! 

How does one change the diagnostic mode? I've hunter all through the S30 dealer menus and can't find the setting.

thanks

**Comment by PeteRager** [comment] 2021-12-10 00:00
An excellent question.

https://resources.lennox.com/fileuploads/b9863d33-f22e-4fc2-ae10-0a143901528bLennox_iComfortS30_Installation_Manual_Setup_Guide.pdf

look at page 50, item 36, it has instructions.

copying @hufman as he is the expert on this subject.

**Comment by PeteRager** [comment] 2021-12-10 00:01
We could add a service call to the integration to make this easier.

**Comment by rugene76** [comment] 2021-12-10 00:25
page 50, item 36? not seeing anything related there....

**Comment by PeteRager** [comment] 2021-12-10 00:34
Should say this. 

√ Run the system in diagnostic mode and verify that it matches actual equip­ ment operation. Go to menu > settings > advance settings > dealer con­ trol center > diagnostics and press the start diagnostics button.

**Comment by PeteRager** [comment] 2021-12-10 16:29
Did this end up working for you?

**Comment by rugene76** [comment] 2021-12-11 15:56
It may be working. I went into start diagnostic and then back out without selecting "stop diagnostics".
I've attached some screen shots of one of my zone's attributes. 
The demand value makes sense and does vary but some of the other attributes need more investigation. For example, the "fan" is on only when just the fan is active with no heating happening (HVAC_action=idle). I had expected the fan attribute to be on when in heating mode. The damper is also always at 100% which seems wrong - I have 4 dampers/zones.

![system idle](https://user-images.githubusercontent.com/60796202/145682930-64727200-8083-48a6-8a04-08620ab21fbe.png)
![fan only](https://user-images.githubusercontent.com/60796202/145682936-f23883d8-22d4-4572-9487-333656b23bc5.png)
![HP heat on](https://user-images.githubusercontent.com/60796202/145682946-861f678d-4d04-4db0-81e7-7c36d97ef968.png)

**Comment by PeteRager** [comment] 2021-12-11 18:02
On the fan attribute, right now I am just copying the value from the Lennox Zone update message.  Lennox has it set to off when the HVAC is running and it is only true when the fan is set to On or Circulate.  In my Config I created a binary template sensor to represent whether the fan is really running (e.g HVAC Mode != Off or Fan == True).  So yes, I think we should change that and have that attribute work as you expected it to.  It’s a simple change - create an issue for it when you have a minute and I’ll put it in the next release.

On the damper, that does look incorrect.  I have a single zone system with no dampers, so my ability to test is limited.  What we’ll want to do is turn debug on for the integration (readme describes how to do this), this will cause all the messages from the S30 to get logged. Then turn some zones on and off so that we get the dampers opening and closing.  Then search in the log for damper (or email to me) and we can see what values get reported and how those compare with what you see in the attributes.

**Comment by PeteRager** [comment] 2021-12-15 13:14
Anything we need to do on this?

**Comment by rugene76** [comment] 2021-12-15 15:22
No, it seems to be working well for my purposes - thanks!

As far as I can tell the demand and damper attributes are correct. Damper = 100 is open, damper = 0 is closed. 

The _inverter_energy attribute is always reading 98 and _inverter_kwh is always 0. So something is wrong there.

btw, I'm using local mode.

as a side note, I use Home Habit as my user interface. Your integration works well with the thermostat widget supplied by Home Habit.

**Comment by PeteRager** [comment] 2021-12-15 21:34
Thanks for the update.   That sounds good. I’ll have to check it out.

On the inverter power - this is still in alpha as it’s only been seen working in one setup.

First step is to check the diagLevel.  There should be an entity called lennoxs30.state, it should have an attribute diagLevel.  If this value is 0 - then the issue is the S30 came out of diag mode.  If so, redo the process to put it into diag mode and see if this diagLevel changes to 2 and if it is 2 then the power sensor should update.

**Comment by rugene76** [comment] 2021-12-15 21:51
DiagLevel was returning 0 so I did the "run diagnostic " procedure but diagLevel still returns 0.

**Comment by PeteRager** [comment] 2021-12-15 23:18
Ok, it sounds that procedure to turn diags on does not work.  When @hufman developed this capability I believe he was using a script to send the diag command to the S30.  We may need his script to try.  I’ll see if I can add a service method to toggle this level as part of the upcoming release.

**Comment by hufman** [comment] 2021-12-16 02:51
This is the command I send to enable diagnostic mode on my system: https://github.com/hufman/lennox_lcc/blob/master/test_lcc.py#L86-L93

**Comment by PeteRager** [comment] 2021-12-16 22:12
I've added the command to the API and Number Entity to Integration and it'll be in the next release (hopefully before NY)

![image](https://user-images.githubusercontent.com/76050312/146456608-6ffeee99-91a7-42b8-a748-1cb74a8a0faf.png)

And then you can set it to 0,1 or 2.

**Closed** 2021-12-24 14:04 UTC
Labels: enhancement

**Comment by PeteRager** [comment] 2021-12-24 14:05
Was automatically closed as changes are made and merged into the upcoming release available by end of year.

**Comment by PeteRager** [comment] 2021-12-28 21:42
release is out, there is a number entity to set the diagnostic level

https://github.com/PeteRager/lennoxs30/releases/tag/v0.2.0
