### ISSUE TITLE
M30 does not send/persist temp setpoints

### ISSUE THREAD

**Issue by mbirkes** [PeteRager/lennoxs30#137] opened 2022-02-03 22:24 UTC
I've successfully integrated using a cloud connection to my system containing 3x M30 thermostats each controlling a separate home unit, but I cannot persist temperature setpoints. 

When sending set_temperature commands, the new setpoints are not set (or not received by the units/cloud service).  This is consistent whether I use the UI entity controls or directly call the climate.set_temperature service on any one of the M30 thermostat entities. 

Everything else seems to function as expected including changing HVAC modes and reading sensors. The state is reporting connected with no error count. 

Also note: while using the service to change both the mode and temp, the HVAC mode will successfully change, but the setpoints remain the prior values, not the new requested values. 
```
service: climate.set_temperature
data:
  hvac_mode: heat_cool
  target_temp_low: 75
  target_temp_high: 79
target:
  entity_id: climate.master_zone_1
```

**Comment by mbirkes** [comment] 2022-02-03 23:02
I found some additional information in the log as a result of attempting to set temperature setpoints. I'm not sure what exact scenario causes it yet:
```
This error originated from a custom integration.

Logger: custom_components.lennoxs30.climate
Source: custom_components/lennoxs30/climate.py:643
Integration: Lennox S30/E30 (documentation)
First occurred: 4:41:37 PM (3 occurrences)
Last logged: 4:59:13 PM

set_temperature System Mode is [cool] unable to set temperature
```

**Comment by PeteRager** [comment] 2022-02-03 23:09
Interesting.  

Please grab the full log messages out of the home assistant log.  Does the error occur whenever you try to set the temperature?  Are you using the stock climate control from HA?

When the system is in cool mode, there is only one setpoint.  This error may indicate that two setpoints are being sent to the service.

**Comment by mbirkes** [comment] 2022-02-03 23:17
So to keep it simple, I tested the following scenario:
Unit is currently set to Cool mode at 77deg (F).
I did 2 tests. One with the stock HA climate control, second with the service command. 


1. Click the down arrow to change temp to 76deg. After one sec it refreshes back to 77
Log from this first test (HA climate control):
```
2022-02-03 17:11:20,903 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000006",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
2022-02-03 17:11:20,903 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000006",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
```

2. Second test. The following command (current state is still at 77 deg in Cool Mode)
```
service: climate.set_temperature
data:
  hvac_mode: cool
  temperature: 76
target:
  entity_id: climate.master_zone_1
```

Log from this test:
```
2022-02-03 17:11:54,023 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000007",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
2022-02-03 17:11:54,023 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000007",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
```

**Comment by PeteRager** [comment] 2022-02-03 23:22
There are no setpoint values in those messages, which is why nothing is happening.  Must be something I don’t understand regarding the M30.  since you have message logging turned on, go change the setpoint from the M30, what is the message we get in the log and does that reflect into the UI?

**Comment by mbirkes** [comment] 2022-02-03 23:22
Here is an additional test.
Current state is still at 77deg in Cool mode
1. Use service to change mode and set temp
```
service: climate.set_temperature
data:
  hvac_mode: heat_cool
  target_temp_high: 78
  target_temp_low: 73
target:
  entity_id: climate.master_zone_1
```

The result is that the state successfully changed to Heat/Cool mode, but the setpoints did not send.
Log

```
2022-02-03 17:19:38,054 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000008",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {
                                "systemMode": "heat and cool"
                            }
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
2022-02-03 17:19:38,054 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000008",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {
                                "systemMode": "heat and cool"
                            }
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
2022-02-03 17:19:38,237 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000009",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
2022-02-03 17:19:38,237 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-000000000009",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
```

**Comment by PeteRager** [comment] 2022-02-03 23:24
Next test, set the thermostat into cool or heat mode from the panel.  Then call that set temperature service without specifying hvac_mode.  We should be seeing a csp or hsp in the message.

**Comment by mbirkes** [comment] 2022-02-03 23:28
Yes, the setpoint reflect in the HA UI when I change the setpoints in my iComfort app. 
Same state 77deg Cool. Change to 76 from icomfort app
Here is the message received:

```
2022-02-03 17:27:14,943 [MainThread  ] [DEBUG]  {
    "messages": [
        {
            "MessageId": "637795276348997981|212084cda8a64a0cbb15aae85ef83b31",
            "SenderId": "**redacted**",
            "TargetID": "mapp079372367644467046827081_mason.birkes@outlook.com",
            "MessageType": "PropertyChange",
            "Data": {
                "schedules": [
                    {
                        "publisher": {
                            "publisherName": "remote"
                        },
                        "id": 16,
                        "schedule": {
                            "periods": [
                                {
                                    "id": 0,
                                    "period": {
                                        "systemMode": "cool",
                                        "hsp": 73.0,
                                        "hspC": 23.0,
                                        "csp": 76.0,
                                        "cspC": 24.5
                                    }
                                }
                            ]
                        }
                    }
                ]
            },
            "AdditionalParameters": null
        },
        {
            "MessageId": "637795276348998651|51ec06823958453d929d71a09135f5c6",
            "SenderId": "**redacted**",
            "TargetID": "mapp079372367644467046827081_mason.birkes@outlook.com",
            "MessageType": "PropertyChange",
            "Data": {
                "zones": [
                    {
                        "publisher": {
                            "publisherName": "lcc"
                        },
                        "status": {
                            "fan": false,
                            "humidity": 30,
                            "temperature": 73,
                            "damper": 0,
                            "heatCoast": false,
                            "defrost": false,
                            "humidityStatus": "good",
                            "period": {
                                "systemMode": "cool",
                                "fanMode": "auto",
                                "husp": 40,
                                "sp": 73,
                                "desp": 50,
                                "csp": 76,
                                "hsp": 73,
                                "hspC": 23,
                                "startTime": 0,
                                "humidityMode": "off",
                                "spC": 23,
                                "cspC": 24.5
                            },
                            "humOperation": "off",
                            "scheduleExceptionIds": [],
                            "balancePoint": "none",
                            "tempOperation": "off",
                            "ventilation": false,
                            "demand": 0,
                            "aux": false,
                            "coolCoast": false,
                            "ssr": false,
                            "temperatureStatus": "good",
                            "temperatureC": 23
                        },
                        "id": 0
                    }
                ]
            },
            "AdditionalParameters": null
        }
    ]
}
2022-02-03 17:27:14,943 [MainThread  ] [DEBUG]  {
    "messages": [
        {
            "MessageId": "637795276348997981|212084cda8a64a0cbb15aae85ef83b31",
            "SenderId": "**redacted**",
            "TargetID": "mapp079372367644467046827081_mason.birkes@outlook.com",
            "MessageType": "PropertyChange",
            "Data": {
                "schedules": [
                    {
                        "publisher": {
                            "publisherName": "remote"
                        },
                        "id": 16,
                        "schedule": {
                            "periods": [
                                {
                                    "id": 0,
                                    "period": {
                                        "systemMode": "cool",
                                        "hsp": 73.0,
                                        "hspC": 23.0,
                                        "csp": 76.0,
                                        "cspC": 24.5
                                    }
                                }
                            ]
                        }
                    }
                ]
            },
            "AdditionalParameters": null
        },
        {
            "MessageId": "637795276348998651|51ec06823958453d929d71a09135f5c6",
            "SenderId": "**redacted**",
            "TargetID": "mapp079372367644467046827081_mason.birkes@outlook.com",
            "MessageType": "PropertyChange",
            "Data": {
                "zones": [
                    {
                        "publisher": {
                            "publisherName": "lcc"
                        },
                        "status": {
                            "fan": false,
                            "humidity": 30,
                            "temperature": 73,
                            "damper": 0,
                            "heatCoast": false,
                            "defrost": false,
                            "humidityStatus": "good",
                            "period": {
                                "systemMode": "cool",
                                "fanMode": "auto",
                                "husp": 40,
                                "sp": 73,
                                "desp": 50,
                                "csp": 76,
                                "hsp": 73,
                                "hspC": 23,
                                "startTime": 0,
                                "humidityMode": "off",
                                "spC": 23,
                                "cspC": 24.5
                            },
                            "humOperation": "off",
                            "scheduleExceptionIds": [],
                            "balancePoint": "none",
                            "tempOperation": "off",
                            "ventilation": false,
                            "demand": 0,
                            "aux": false,
                            "coolCoast": false,
                            "ssr": false,
                            "temperatureStatus": "good",
                            "temperatureC": 23
                        },
                        "id": 0
                    }
                ]
            },
            "AdditionalParameters": null
        }
    ]
}
```

**Comment by mbirkes** [comment] 2022-02-03 23:31
Next test. 
Same state 77deg Cool mode.
1. Change temp only
```
service: climate.set_temperature
data:
  temperature: 76
target:
  entity_id: climate.master_zone_1
```
```
2022-02-03 17:30:00,798 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-00000000000c",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}
2022-02-03 17:30:00,798 [MainThread  ] [DEBUG]  {
    "MessageType": "Command",
    "SenderID": "**redacted**",
    "MessageID": "00000000-0000-0000-0000-00000000000c",
    "TargetID": "40509c58-cc1c-4937-bc31-8d92d98902d0",
    "Data": {
        "schedules": [
            {
                "schedule": {
                    "periods": [
                        {
                            "id": 0,
                            "period": {}
                        }
                    ]
                },
                "id": 16
            }
        ]
    }
}

```

**Comment by PeteRager** [comment] 2022-02-03 23:31
That looks correct and consistent with S30 data.  Are you using / can you try the default Thermostat card in Lovelace to do the setpoint?

**Comment by mbirkes** [comment] 2022-02-03 23:33
i get the same results and logs with the lovelace card, the entity control screen, and the direct service command.

**Comment by PeteRager** [comment] 2022-02-03 23:36
Yep, looks like it is busted on your system.

Looks like I'm going to need a dump of your configuration.  I can load it into a simulator and figure out what is going on.

Easiest way is to turn on the message logging to a file, reload the integration / restart HA.  Then send to me once the system is up and you've performed a couple setpoints from the M30 and HA.  Then we'll have the complete data set in that file.

 Either post here (make sure you have the Personal Information not included) or I can give you my email.

You are running 0.2.2 or 0.2.1?

**Comment by mbirkes** [comment] 2022-02-03 23:38
I'm running 2.2.  How can I get your email?  I will get you all that information here shortly when I am able to reset everything and send it to you. If you think of anything else, post it here in the meantime

**Comment by PeteRager** [comment] 2022-02-03 23:41
Ok.  It may need the debug information turned on in home assistant log also, I'd like to see the debug output around those setpoint commands..  Readme has the steps.  

That plus the message log files.

pete dot sage at icloud dot com

**Comment by mbirkes** [comment] 2022-02-03 23:43
thanks, I'll be in touch. Great work by the way on everything, if we can just work out this one snag...

**Comment by PeteRager** [comment] 2022-02-04 01:59
Is your M30 configured to use “single setpoint mode” or “perfect mode”?  When it’s in heat_cool do you see one setpoint or two on the M30 display?

**Comment by mbirkes** [comment] 2022-02-04 02:19
I just sent you an email. 
I see two setpoints in dual mode. The tests I sent in the logs were in heat-only mode

**Comment by mbirkes** [comment] 2022-02-04 02:22
also, the M30 doesn't support Perfect Temp mode it seems. See this chart
https://resources.lennox.com/fileuploads/2f274b6f-3120-4ce2-9091-bd7fcddc6b7bThermostat_Product_Comparison_Chart.pdf

**Comment by PeteRager** [comment] 2022-02-04 14:20
That appears to be key to the issue.  Since the S30 and E30 support perfect mode, the current setting comes through in the messages.  Since the M30 does not support it, it does not include the current setting in its messages.  The code is expecting single setpoint mode to be True or False; for the M30 its is uninitialized with a value of None.  Hence the code does nothing.  This will be an easy bug to fix.   Looks like this just effects the API, not the integration.  So once I get it patched in the API, we can just update the integrations manifest.json to pull the new version.

**Comment by mbirkes** [comment] 2022-02-04 15:10
That's awesome. Thanks for the quick turnaround. Just let me know what I need to do once you have the solution completed.

**Comment by PeteRager** [comment] 2022-02-04 15:22
Linking in the pull request for this issue.  

https://github.com/PeteRager/lennoxs30api/pull/38

**Comment by PeteRager** [comment] 2022-02-04 15:44
I have a test version of the API available for you.  It should fix this issue.  To grab it, we'll need to update the integrations manifest file to pull the new version.

1. Go into custom_components/lennoxs30
2. Edit the manifest.json file

There should be a line that says this:

```
    "requirements": ["lennoxs30api==0.1.5"],
```

Change it to this and save.

```
    "requirements": ["lennoxs30api==0.1.6"],
```

Verify it is changed.

Restart HA.  Startup will take bit longer as it fetches the new version of the API.

Once confirmed it fixes the issue, I'll create a 0.2.3 release.

**Comment by mbirkes** [comment] 2022-02-04 18:38
Thanks. With a first pass, it all seems to be working as expected. If you would like me to specifically test anything in particular, please let me know. 

I tested a few scenarios with the climate UI and the service directly with success. A few times I had to 'redo' the command, but I think this has more to do with the cloud service latency and reliability. This has always been finicky even with the native apps and other services like google home.  I wish I could use local/lan connections with the M30.

**Comment by PeteRager** [comment] 2022-02-04 19:38
Thanks for testing.  The only change is for the setpoint code and it sound like functionally it works.

Regarding the cloud latency - that definitely exists.    By default the integration checks the cloud for changes every 10 seconds - that’s the scan_interval in the config.  After executing a command, the integration goes into fast scan mode using a different interval (0.75 seconds) and does this 10 times (not configurable), and after that is goes back into 10 seconds poll mode. However, sometimes it can take up to 30 seconds for the setpoint to get processed.  You may want to try increasing the fast scan interval to 3s to see if this helps on the response.  Either way, the setpoint should get processed it may just take a while.  If you want to gather message logs on this and identify where the setpoints never get processed I’d be happy to look at it.

The other item to keep a check on is the lennoxs30.state object.   That has attributes that track comm errors to the cloud.  If you start seeing lots of 500s, that’s a sign there are issues going on in Lennox cloud.

For resiliency in automations, I use a script that sets the temperature, delays, check to see if climate object got updates, if not tries it again, delays longer.   I do this 3 times.  I have a NEST on my furnace and every now and then it drops setpoints.

**Comment by PeteRager** [comment] 2022-02-04 23:22
I’m going to create a release in the AM and at that same time we’ll close this specific issue.  If others arise we can create new issues?

**Comment by mbirkes** [comment] 2022-02-05 01:03
Sounds like a plan. Thanks for the detailed response, that makes sense and helps. This gets me where I need to be for now and I'll open additional issues if they arise. 

If you need any particular help specifically around the M30 integration, just let me know.

**Closed** 2022-02-05 13:40 UTC
Labels: bug
